name: kod_sozluk_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API INTEGRATION
  dio: ^4.0.0                           # HTTP Client
  pretty_dio_logger: ^1.1.1             # HTTP Client Logger
  json_serializable: ^5.0.2             # JSON Serializer Helper
  json_annotation: ^4.1.0               # JSON Serializer Dependency

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0                  # Google Fonts
  flutter_easyloading: ^3.0.3           # Loading Indicator
  font_awesome_flutter: ^9.1.0          # Icons
  material_color_generator: ^1.1.0      # Material Color Generator

  # STATE & DATA MANAGEMENT & CONVERTING
  intl: ^0.17.0                         # Date Time Parsing & Formatting
  get: ^4.3.8                           # Get Library
  get_it: ^7.2.0                        # Dependency Injection Alternative
  flutter_bloc: ^7.3.0                  # State Management
  shared_preferences: ^2.0.8            # Persistent Storage
  easy_localization: ^3.0.0             # Multi-Lang Support
  connectivity: ^3.0.6                  # Connection controller

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

#  fonts:
#    - family: Icons
#      fonts:
#        - asset: assets/icons/Icons.ttf
#
  assets:
    - assets/images/
    - assets/languages/
